# Generated by Django 5.1.1 on 2024-10-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('job', models.CharField(max_length=100)),
                ('hobby', models.CharField(max_length=100)),
            ],
        ),
    ]
