# Generated by Django 3.2.2 on 2024-10-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_job', models.CharField(max_length=100)),
                ('user_contact', models.CharField(max_length=100)),
                ('user_password', models.CharField(max_length=128)),
                ('user_dob_year', models.IntegerField()),
                ('user_dob_month', models.IntegerField()),
                ('user_dob_day', models.IntegerField()),
                ('user_gender', models.CharField(max_length=50)),
                ('user_custom_gender', models.CharField(blank=True, max_length=100, null=True)),
                ('user_hobbies', models.JSONField(default=list)),
            ],
        ),
    ]
