# Generated by Django 3.2.25 on 2024-10-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('dob_year', models.IntegerField()),
                ('dob_month', models.IntegerField()),
                ('dob_day', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('custom_gender', models.CharField(blank=True, max_length=100, null=True)),
                ('hobbies', models.JSONField(default=list)),
            ],
        ),
        migrations.DeleteModel(
            name='DataEntry',
        ),
    ]
