# Generated by Django 3.2.25 on 2024-10-29 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0003_alter_userprofile_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='contact',
            new_name='user_contact',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='custom_gender',
            new_name='user_custom_gender',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='dob_day',
            new_name='user_dob_day',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='dob_month',
            new_name='user_dob_month',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='dob_year',
            new_name='user_dob_year',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='gender',
            new_name='user_gender',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='hobbies',
            new_name='user_hobbies',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='job',
            new_name='user_job',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='name',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='password',
            new_name='user_password',
        ),
    ]
